name: 🚀 Production Deploy

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: 🧪 Testing Frontend
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         cache: 'npm'
  #     - run: npm install
  #     - run: npm test
      
  build:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-repository-action@v1.0.0
        with:
          hostname: ${{ vars.CPANEL_DOMAIN }}
          repository_root: ${{ secrets.CPANEL_REPOSITORIES_PATH }}/${{ vars.REPOSITORY_NAME }}-dev
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          cpanel_token: ${{ secrets.CPANEL_API_TOKEN_DEV }}
          branch: main
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"